esphome:
  name: tempsensor

external_components:
  - source:
      type: local
      path: components
    components: [adt7420]

esp32:
  board: esp32dev
  framework:
    type: arduino

i2c:
  sda: 33
  scl: 32
  scan: True

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""

sensor:
  - platform: adt7420
    temperature:
      name: "Temperature Sensor"
    address: 0x48 # I2C address (0x48-0x4B depending on A1/A0 pins)
    update_interval: 15s

wifi:
  ssid: "HomeSweetHome"
  password: "Century751"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tempsensor Fallback Hotspot"
    password: "NaVJuPAk2RL7"

captive_portal:
